In [169]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split , cross_val_score
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler

In [151]:
df = pd.read_csv("heart.csv")
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [152]:
df.shape

(918, 12)

In [153]:
df1 = df[(df.MaxHR <= (df.MaxHR.mean()+ df.MaxHR.std()*3)) & (df.MaxHR > (df.MaxHR.mean()- df.MaxHR.std()*3))]
df1.shape

(917, 12)

In [154]:
df2 = df1[(df.Cholesterol <= (df.Cholesterol.mean()+ df.Cholesterol.std()*3)) & (df.Cholesterol > (df.Cholesterol.mean()- df.Cholesterol.std()*3))]
df2.shape

C:\Users\Acer\AppData\Local\Temp\ipykernel_11440\745214855.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df1[(df.Cholesterol <= (df.Cholesterol.mean()+ df.Cholesterol.std()*3)) & (df.Cholesterol > (df.Cholesterol.mean()- df.Cholesterol.std()*3))]


(914, 12)

In [155]:
df3 = df2[(df.RestingBP <= (df.RestingBP.mean()+ df.RestingBP.std()*3)) & (df.RestingBP > (df.RestingBP.mean()- df.RestingBP.std()*3))]
df3.shape


C:\Users\Acer\AppData\Local\Temp\ipykernel_11440\1924408719.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df3 = df2[(df.RestingBP <= (df.RestingBP.mean()+ df.RestingBP.std()*3)) & (df.RestingBP > (df.RestingBP.mean()- df.RestingBP.std()*3))]


(906, 12)

In [156]:
df3.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [157]:
LE =LabelEncoder()

In [158]:
df3['Sex'] =LE.fit_transform(df3['Sex'])
df3['ChestPainType'] =LE.fit_transform(df3['ChestPainType'])
df3['RestingECG'] =LE.fit_transform(df3['RestingECG'])
df3['ExerciseAngina'] =LE.fit_transform(df3['ExerciseAngina'])
df3['ST_Slope'] =LE.fit_transform(df3['ST_Slope'])
df3

C:\Users\Acer\AppData\Local\Temp\ipykernel_11440\793500794.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Sex'] =LE.fit_transform(df3['Sex'])
C:\Users\Acer\AppData\Local\Temp\ipykernel_11440\793500794.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['ChestPainType'] =LE.fit_transform(df3['ChestPainType'])
C:\Users\Acer\AppData\Local\Temp\ipykernel_11440\793500794.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    1              1        140          289          0           1   
1     49    0              2        160          180          0           1   
2     37    1              1        130          283          0           2   
3     48    0              0        138          214          0           1   
4     54    1              2        150          195          0           1   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    1              3        110          264          0           1   
914   68    1              0        144          193          1           1   
915   57    1              0        130          131          0           1   
916   57    0              1        130          236          0           0   
917   38    1              2        138          175          0           1   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0      172               0      0.0         2             0  
1      156               0      1.0         1             1  
2       98               0      0.0         2             0  
3      108               1      1.5         1             1  
4      122               0      0.0         2             0  
..     ...             ...      ...       ...           ...  
913    132               0      1.2         1             1  
914    141               0      3.4         1             1  
915    115               1      1.2         1             1  
916    174               0      0.0         1             1  
917    173               0      0.0         2             0  

[906 rows x 12 columns]

In [159]:
    ohe = OneHotEncoder()
    transformer = ColumnTransformer(
        transformers = [
            ("ohe",OneHotEncoder(sparse_output=False),[0])
        ]
    )

In [160]:
x1 = transformer.fit_transform(df3[["ChestPainType"]].values)
x1


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       ...,
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [161]:
x2 =transformer.fit_transform(df3[["RestingECG"]])
x2.shape

(906, 3)

In [162]:
x3 = transformer.fit_transform(df3[["ST_Slope"]])
x3.shape

(906, 3)

In [163]:
x4= df3.drop(["RestingECG","ST_Slope","ChestPainType","HeartDisease"],axis=1)
x4.shape

(906, 8)

In [164]:
x_final = np.concatenate((x1,x2,x3,x4),axis=1)

In [165]:
y = df3.HeartDisease
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 906, dtype: int64

In [166]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x_final)
x_scaled

array([[-1.08289513,  2.07322107, -0.5322463 , ...,  1.38940616,
        -0.8232726 , -0.83125986],
       [-1.08289513, -0.48234123,  1.87882942, ...,  0.75618606,
        -0.8232726 ,  0.10838011],
       [-1.08289513,  2.07322107, -0.5322463 , ..., -1.5392368 ,
        -0.8232726 , -0.83125986],
       ...,
       [ 0.92345045, -0.48234123, -0.5322463 , ..., -0.86644044,
         1.2146645 ,  0.2963081 ],
       [-1.08289513,  2.07322107, -0.5322463 , ...,  1.46855867,
        -0.8232726 , -0.83125986],
       [-1.08289513, -0.48234123,  1.87882942, ...,  1.42898242,
        -0.8232726 , -0.83125986]])

In [167]:
x_train,x_test,y_train,y_test =train_test_split(x_scaled,y,stratify=y,random_state=10)

In [171]:
svm = SVC().fit(x_train,y_train)
svm.score(x_test,y_test)

0.8766519823788547

In [172]:
tree = DecisionTreeClassifier().fit(x_train,y_train)
tree.score(x_test,y_test)

0.8061674008810573

In [174]:
bag_model = BaggingClassifier(
    estimator=SVC(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
).fit(x_train,y_train)
bag_model.oob_score_

0.8674521354933726

In [176]:
bag_model.score(x_test,y_test)

0.8678414096916299

In [177]:
bag_model2 = BaggingClassifier(
    estimator=SVC(),
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)

In [179]:
score =cross_val_score(bag_model2,x_scaled,y,cv=5)
score

array([0.86813187, 0.81767956, 0.83977901, 0.83977901, 0.74585635])

In [180]:
score.mean()

0.8222451581567605